"""empty message

Revision ID: 11307cbf9190
Revises: 8abc6ad308e5
Create Date: 2017-01-08 20:17:57.055492

"""

# revision identifiers, used by Alembic.
revision = '11307cbf9190'
down_revision = '8abc6ad308e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    ### end Alembic commands ###
