"""empty message

Revision ID: 8abc6ad308e5
Revises: 99a0ecaaba04
Create Date: 2017-01-07 18:05:27.671097

"""

# revision identifiers, used by Alembic.
revision = '8abc6ad308e5'
down_revision = '99a0ecaaba04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    ### end Alembic commands ###
