"""empty message

Revision ID: 99a0ecaaba04
Revises: 9f875c90ef45
Create Date: 2016-12-02 08:42:35.737772

"""

# revision identifiers, used by Alembic.
revision = '99a0ecaaba04'
down_revision = '9f875c90ef45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    ### end Alembic commands ###
